name: Build and Deploy Salesforce Elements to Org #Author: nbhaumik/Jul-2024
on:
  push:
    branches: [ feature,dev, int, uat, master ]
  workflow_dispatch:

jobs:
  DEV-deploy:
    runs-on: ubuntu-latest
    if: endsWith(github.ref, 'Dev')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install SFDX CLI
        run: npm install sfdx-cli --global

      - name: Authorize SF Org
        run: sfdx force:auth:jwt:grant --clientid 3MVG933SC8s3vkAU9CQblG8.NEs1i8_5_y.9HRJXzfIjPtg7eHmIhhRN1mt_7OzxfcRKvfROmSCH6AbriK3G7 --jwtkeyfile ./buildfiles/server.key --username selva.kumar@milestone.tech.main.dev01 --instanceurl https://login.salesforce.com/ -a feature

      - name: Convert to Deploy Source
        run: sfdx force:source:convert -r ./force-app -d ./toDeploy

      - name: Run Validation on Deploy Source
        run: sfdx force:source:deploy -c -x manifest/package.xml -u Dev

      - name: Deploy to SF Org
        run: sfdx force:source:deploy -x manifest/package.xml -u Dev
